<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Wasaly.PL-d3c19f52-8f31-41ac-91c5-20a3b6c20f12</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wasaly.BLL\Wasaly.BLL.csproj" />
  </ItemGroup>

</Project>
